// Mappage des icônes vers les émojis
const iconToEmoji = {
  'dark_mode': '🌓',
  'home': '🏠',
  'music_note': '🔊',
  'volume_off': '🔇',
  'calendar_today': '📅',
  'close': '✖️',
  'chevron_left': '⬅️',
  'chevron_right': '➡️',
  'schedule': '⏱️',
  'wb_sunny': '☀️',
  'devices': '📱',
  'offline_bolt': '⚡',
  'menu': '☰',
  'search': '🔍',
  'settings': '⚙️',
  'info': 'ℹ️',
  'help': '❓',
  'arrow_back': '🔙',
  'arrow_forward': '🔜',
  'check': '✅',
  'cancel': '❌',
  'add': '➕',
  'remove': '➖',
  'edit': '✏️',
  'delete': '🗑️',
  'refresh': '🔄',
  'download': '⬇️',
  'upload': '⬆️',
  'favorite': '❤️',
  'star': '⭐',
  'warning': '⚠️',
  'error': '❌',
  'check_circle': '✅',
  'info_outline': 'ℹ️',
  'lock': '🔒',
  'lock_open': '🔓',
  'visibility': '👁️',
  'visibility_off': '👁️‍🗨️',
  'person': '👤',
  'group': '👥',
  'notifications': '🔔',
  'email': '✉️',
  'phone': '📞',
  'link': '🔗',
  'attachment': '📎',
  'cloud': '☁️',
  'cloud_done': '☁️✅',
  'cloud_download': '☁️⬇️',
  'cloud_upload': '☁️⬆️',
  'cloud_off': '☁️❌',
  'wifi': '📶',
  'wifi_off': '📵',
  'battery_alert': '🔋',
  'battery_charging_full': '🔌',
  'battery_full': '🔋',
  'battery_std': '🔋',
  'battery_unknown': '🔋❓',
  'gps_fixed': '📍',
  'gps_not_fixed': '📍❌',
  'gps_off': '📍❌',
  'location_disabled': '📍❌',
  'location_searching': '🔍📍',
  'my_location': '📍',
  'place': '📍',
  'map': '🗺️',
  'navigation': '🧭',
  'compass_calibration': '🧭',
  'layers': '🗺️',
  'layers_clear': '🗺️❌',
  'terrain': '🏔️',
  'directions': '🚗',
  'directions_bike': '🚴',
  'directions_boat': '⛵',
  'directions_bus': '🚌',
  'directions_car': '🚗',
  'directions_railway': '🚆',
  'directions_run': '🏃',
  'directions_subway': '🚇',
  'directions_transit': '🚊',
  'directions_walk': '🚶',
  'flight': '✈️',
  'hotel': '🏨',
  'restaurant': '🍽️',
  'school': '🏫',
  'shopping_cart': '🛒',
  'store': '🏪',
  'wc': '🚻',
  'access_time': '⏰',
  'alarm': '⏰',
  'av_timer': '⏱️',
  'schedule': '📅',
  'timer': '⏱️',
  'timer_off': '⏱️❌',
  'today': '📅',
  'update': '🔄',
  'accessibility': '♿',
  'account_balance': '🏦',
  'account_balance_wallet': '💳',
  'build': '🛠️',
  'credit_card': '💳',
  'dashboard': '📊',
  'delete_forever': '🗑️',
  'description': '📄',
  'dns': '🌐',
  'done': '✅',
  'done_all': '✅✅',
  'exit_to_app': '🚪',
  'find_in_page': '🔍',
  'grade': '⭐',
  'help_outline': '❓',
  'highlight_off': '❌',
  'home': '🏠',
  'https': '🔒',
  'info': 'ℹ️',
  'input': '↩️',
  'launch': '🚀',
  'list': '📋',
  'lock_open': '🔓',
  'lock_outline': '🔒',
  'loyalty': '💎',
  'markunread_mailbox': '📬',
  'note_add': '📝',
  'offline_bolt': '⚡',
  'opacity': '💧',
  'open_in_browser': '🌐',
  'open_in_new': '↗️',
  'pageview': '📄',
  'payment': '💳',
  'perm_camera_mic': '🎤',
  'perm_contact_calendar': '📅',
  'pets': '🐾',
  'picture_in_picture': '🖼️',
  'query_builder': '⏱️',
  'question_answer': '💬',
  'receipt': '🧾',
  'redeem': '🎁',
  'search': '🔍',
  'settings': '⚙️',
  'settings_applications': '⚙️',
  'settings_backup_restore': '🔄',
  'settings_bluetooth': '📶',
  'settings_brightness': '💡',
  'settings_cell': '📱',
  'settings_ethernet': '🌐',
  'settings_input_antenna': '📡',
  'settings_input_component': '🎛️',
  'settings_input_hdmi': '📺',
  'settings_input_svideo': '📺',
  'settings_overscan': '🖥️',
  'settings_phone': '📱',
  'settings_power': '🔌',
  'settings_remote': '📱',
  'settings_voice': '🎙️',
  'shop': '🛍️',
  'shopping_basket': '🛒',
  'shopping_cart': '🛒',
  'speaker_notes': '🗒️',
  'spellcheck': '✓',
  'stars': '⭐',
  'store': '🏪',
  'subject': '📄',
  'supervised_user_circle': '👥',
  'supervisor_account': '👥',
  'tab': '📑',
  'tab_unselected': '📑',
  'theaters': '🎬',
  'thumb_down': '👎',
  'thumb_up': '👍',
  'thumbs_up_down': '👍👎',
  'toc': '📑',
  'today': '📅',
  'toll': '💰',
  'touch_app': '👆',
  'track_changes': '🔄',
  'translate': '🌐',
  'trending_down': '📉',
  'trending_flat': '➡️',
  'trending_up': '📈',
  'turned_in': '📌',
  'update': '🔄',
  'verified_user': '✅',
  'view_agenda': '📋',
  'view_array': '📋',
  'view_carousel': '🖼️',
  'view_column': '📋',
  'view_day': '📅',
  'view_headline': '📰',
  'view_list': '📋',
  'view_module': '⏹️',
  'view_quilt': '🧩',
  'view_stream': '📋',
  'view_week': '📅',
  'visibility': '👁️',
  'visibility_off': '👁️‍🗨️',
  'work': '💼',
  'youtube_searched_for': '🔍',
  'zoom_in': '🔍➕',
  'zoom_out': '🔍➖',
  'add_a_photo': '📷',
  'add_photo_alternate': '🖼️',
  'adjust': '🎨',
  'assistant': '💁',
  'assistant_photo': '🌅',
  'audiotrack': '🎵',
  'blur_circular': '⭕',
  'blur_linear': '➖',
  'blur_off': '✖️',
  'blur_on': '⭕',
  'brightness_1': '🔘',
  'brightness_2': '🔳',
  'brightness_3': '🔲',
  'brightness_4': '⬛',
  'brightness_5': '⬜',
  'brightness_6': '🔳',
  'brightness_7': '🔲',
  'broken_image': '🖼️❌',
  'brush': '🖌️',
  'camera': '📷',
  'camera_alt': '📷',
  'camera_front': '📱',
  'camera_rear': '📱',
  'camera_roll': '🎞️',
  'center_focus_strong': '🎯',
  'center_focus_weak': '🎯',
  'collections': '🖼️',
  'color_lens': '🎨',
  'colorize': '🎨',
  'compare': '🔄',
  'control_point': '➕',
  'control_point_duplicate': '➕➕',
  'crop': '✂️',
  'crop_3_2': '3:2',
  'crop_5_4': '5:4',
  'crop_7_5': '7:5',
  'crop_16_9': '16:9',
  'crop_din': '🖼️',
  'crop_free': '✂️',
  'crop_landscape': '🌄',
  'crop_original': '🖼️',
  'crop_portrait': '👤',
  'crop_rotate': '🔄',
  'crop_square': '⬛',
  'dehaze': '☀️',
  'details': '🔍',
  'edit': '✏️',
  'exposure': '🌓',
  'exposure_neg_1': '➖1',
  'exposure_neg_2': '➖2',
  'exposure_plus_1': '➕1',
  'exposure_plus_2': '➕2',
  'exposure_zero': '0',
  'filter': '🖌️',
  'filter_1': '1️⃣',
  'filter_2': '2️⃣',
  'filter_3': '3️⃣',
  'filter_4': '4️⃣',
  'filter_5': '5️⃣',
  'filter_6': '6️⃣',
  'filter_7': '7️⃣',
  'filter_8': '8️⃣',
  'filter_9': '9️⃣',
  'filter_9_plus': '9️⃣➕',
  'filter_b_and_w': '⚫⚪',
  'filter_center_focus': '🎯',
  'filter_drama': '🌧️',
  'filter_frames': '🖼️',
  'filter_hdr': '🌄',
  'filter_none': '🖼️',
  'filter_tilt_shift': '🎯',
  'filter_vintage': '🖼️',
  'flare': '✨',
  'flash_auto': '⚡',
  'flash_off': '⚡❌',
  'flash_on': '⚡',
  'flip': '🔄',
  'flip_camera_android': '📱',
  'flip_camera_ios': '📱',
  'gradient': '🌈',
  'grain': '🔘',
  'grid_off': '⏹️',
  'grid_on': '⏹️',
  'hdr_off': 'HDR❌',
  'hdr_on': 'HDR',
  'hdr_strong': 'HDR➕',
  'hdr_weak': 'HDR➖',
  'healing': '❤️',
  'image': '🖼️',
  'image_aspect_ratio': '🖼️',
  'image_search': '🔍',
  'iso': 'ISO',
  'landscape': '🏞️',
  'leak_add': '💧',
  'leak_remove': '💧❌',
  'lens': '🔍',
  'linked_camera': '📷',
  'looks': '🎨',
  'looks_3': '3D',
  'looks_4': '4️⃣',
  'looks_5': '5️⃣',
  'looks_6': '6️⃣',
  'looks_one': '1️⃣',
  'looks_two': '2️⃣',
  'loupe': '🔍',
  'monochrome_photos': '⚫⚪',
  'movie_creation': '🎬',
  'movie_filter': '🎥',
  'music_note': '🎵',
  'music_off': '🎵❌',
  'nature': '🌳',
  'nature_people': '👥🌳',
  'navigate_before': '⬅️',
  'navigate_next': '➡️',
  'palette': '🎨',
  'panorama': '🌅',
  'panorama_fish_eye': '🌅',
  'panorama_horizontal': '🌄',
  'panorama_vertical': '🌅',
  'panorama_wide_angle': '🌅',
  'photo': '🖼️',
  'photo_album': '📔',
  'photo_camera': '📷',
  'photo_filter': '🎨',
  'photo_library': '📚',
  'photo_size_select_actual': '🖼️',
  'photo_size_select_large': '🖼️',
  'photo_size_select_small': '🖼️',
  'picture_as_pdf': '📄',
  'portrait': '👤',
  'remove_red_eye': '👁️',
  'rotate_90_degrees_ccw': '🔄',
  'rotate_left': '🔄',
  'rotate_right': '🔄',
  'shutter_speed': '⏱️',
  'slideshow': '🖼️',
  'straighten': '📏',
  'style': '🎨',
  'switch_camera': '🔄',
  'switch_video': '🎥',
  'tag_faces': '😊',
  'texture': '🔳',
  'timelapse': '⏱️',
  'timer': '⏱️',
  'timer_10': '⏱️🔟',
  'timer_3': '⏱️3️⃣',
  'timer_off': '⏱️❌',
  'tonality': '🎨',
  'transform': '🔄',
  'tune': '🎛️',
  'view_comfy': '🖼️',
  'view_compact': '🖼️',
  'vignette': '🖼️',
  'wb_auto': '⚪',
  'wb_cloudy': '☁️',
  'wb_incandescent': '💡',
  'wb_iridescent': '🌈',
  'wb_sunny': '☀️',
  '360': '🔄',
  'add_location': '📍',
  'atm': '🏧',
  'beenhere': '✅',
  'category': '📦',
  'compass_calibration': '🧭',
  'departure_board': '🚌',
  'directions': '🚗',
  'directions_bike': '🚴',
  'directions_boat': '⛵',
  'directions_bus': '🚌',
  'directions_car': '🚗',
  'directions_railway': '🚆',
  'directions_run': '🏃',
  'directions_subway': '🚇',
  'directions_transit': '🚊',
  'directions_walk': '🚶',
  'edit_attributes': '✏️',
  'edit_location': '📍',
  'ev_station': '⛽',
  'fastfood': '🍔',
  'flight': '✈️',
  'hotel': '🏨',
  'layers': '🗺️',
  'layers_clear': '🗑️',
  'local_activity': '🎟️',
  'local_airport': '✈️',
  'local_atm': '🏧',
  'local_bar': '🍸',
  'local_cafe': '☕',
  'local_car_wash': '🚗💦',
  'local_convenience_store': '🏪',
  'local_dining': '🍽️',
  'local_drink': '🥤',
  'local_florist': '🌸',
  'local_gas_station': '⛽',
  'local_grocery_store': '🛒',
  'local_hospital': '🏥',
  'local_hotel': '🏨',
  'local_laundry_service': '👕',
  'local_library': '📚',
  'local_mall': '🏬',
  'local_movies': '🎬',
  'local_offer': '🏷️',
  'local_parking': '🅿️',
  'local_pharmacy': '💊',
  'local_phone': '📞',
  'local_pizza': '🍕',
  'local_play': '🎭',
  'local_post_office': '📮',
  'local_printshop': '🖨️',
  'local_see': '🏖️',
  'local_shipping': '🚚',
  'local_taxi': '🚕',
  'map': '🗺️',
  'money': '💰',
  'my_location': '📍',
  'navigation': '🧭',
  'near_me': '📍',
  'not_listed_location': '❓',
  'person_pin': '👤📍',
  'person_pin_circle': '👤📍',
  'pin_drop': '📍',
  'place': '📍',
  'rate_review': '⭐',
  'restaurant': '🍽️',
  'restaurant_menu': '📋',
  'satellite': '🛰️',
  'store_mall_directory': '🏬',
  'streetview': '🌍',
  'subway': '🚇',
  'terrain': '🗻',
  'traffic': '🚦',
  'train': '🚆',
  'tram': '🚊',
  'transfer_within_a_station': '🚶‍♂️',
  'transit_enterexit': '🚇',
  'trip_origin': '🔘',
  'zoom_out_map': '🔍',
  'apps': '⬛',
  'arrow_back': '⬅️',
  'arrow_back_ios': '⬅️',
  'arrow_downward': '⬇️',
  'arrow_drop_down': '⬇️',
  'arrow_drop_down_circle': '⬇️',
  'arrow_drop_up': '⬆️',
  'arrow_forward': '➡️',
  'arrow_forward_ios': '➡️',
  'arrow_left': '⬅️',
  'arrow_right': '➡️',
  'arrow_upward': '⬆️',
  'cancel': '✖️',
  'check': '✓',
  'chevron_left': '‹',
  'chevron_right': '›',
  'close': '✖️',
  'expand_less': '▲',
  'expand_more': '▼',
  'first_page': '«',
  'fullscreen': '⛶',
  'fullscreen_exit': '⛶',
  'last_page': '»',
  'menu': '☰',
  'more_horiz': '⋯',
  'more_vert': '⋮',
  'refresh': '🔄',
  'subdirectory_arrow_left': '↩️',
  'subdirectory_arrow_right': '↪️',
  'unfold_less': '△',
  'unfold_more': '▽',
  'adb': '🤖',
  'airline_seat_flat': '💺',
  'airline_seat_flat_angled': '💺',
  'airline_seat_individual_suite': '💺',
  'airline_seat_legroom_extra': '💺',
  'airline_seat_legroom_normal': '💺',
  'airline_seat_legroom_reduced': '💺',
  'airline_seat_recline_extra': '💺',
  'airline_seat_recline_normal': '💺',
  'bluetooth_audio': '🎧',
  'confirmation_number': '🎫',
  'disc_full': '💿',
  'do_not_disturb': '🔕',
  'do_not_disturb_alt': '🔕',
  'drive_eta': '⏱️',
  'enhanced_encryption': '🔒',
  'event_available': '✅',
  'event_busy': '❌',
  'event_note': '📝',
  'folder_special': '📁',
  'live_tv': '📺',
  'mms': '📨',
  'more': '⋯',
  'network_check': '📶',
  'network_locked': '🔒',
  'no_encryption': '🔓',
  'ondemand_video': '📺',
  'personal_video': '📺',
  'phone_bluetooth_speaker': '📱',
  'phone_forwarded': '📱',
  'phone_in_talk': '📱',
  'phone_locked': '📱',
  'phone_missed': '📱',
  'phone_paused': '📱',
  'power': '🔌',
  'priority_high': '❗',
  'sd_card': '💾',
  'sim_card_alert': '📱',
  'sms': '💬',
  'sms_failed': '❌',
  'sync': '🔄',
  'sync_disabled': '🔄❌',
  'sync_problem': '❓',
  'system_update': '🔄',
  'tap_and_play': '👆▶️',
  'time_to_leave': '⏱️',
  'vibration': '📳',
  'voice_chat': '🗣️',
  'vpn_lock': '🔒',
  'wc': '🚻',
  'wifi': '📶',
  'ac_unit': '❄️',
};

// Fonction pour remplacer les icônes par des émojis
function replaceIconsWithEmojis() {
  const icons = document.querySelectorAll('.material-icons');
  let replacedCount = 0;
  
  icons.forEach(icon => {
    const iconName = icon.textContent.trim();
    if (iconToEmoji[iconName]) {
      // Sauvegarder le nom de l'icône dans un attribut data
      if (!icon.hasAttribute('data-icon-name')) {
        icon.setAttribute('data-icon-name', iconName);
        icon.textContent = iconToEmoji[iconName];
        replacedCount++;
      }
    }
  });
  
  // Si aucune icône n'a été remplacée, essayer avec une approche différente
  if (replacedCount === 0) {
    // Essayer avec les icônes qui pourraient être dans des éléments span
    const spans = document.querySelectorAll('span');
    spans.forEach(span => {
      if (span.classList && span.classList.contains('material-icons')) {
        const iconName = span.textContent.trim();
        if (iconToEmoji[iconName] && !span.hasAttribute('data-icon-name')) {
          span.setAttribute('data-icon-name', iconName);
          span.textContent = iconToEmoji[iconName];
        }
      }
    });
  }
  
  // Vérifier à nouveau après un court délai pour les icônes chargées dynamiquement
  setTimeout(() => {
    const dynamicIcons = document.querySelectorAll('.material-icons:not([data-icon-name])');
    dynamicIcons.forEach(icon => {
      const iconName = icon.textContent.trim();
      if (iconToEmoji[iconName]) {
        icon.setAttribute('data-icon-name', iconName);
        icon.textContent = iconToEmoji[iconName];
      }
    });
  }, 500);
}

// Fonction pour restaurer les icônes originales
function restoreIcons() {
  const icons = document.querySelectorAll('[data-icon-name]');
  icons.forEach(icon => {
    const originalIcon = icon.getAttribute('data-icon-name');
    icon.textContent = originalIcon;
    icon.removeAttribute('data-icon-name');
  });
}

// Vérifier l'état de la connexion et mettre à jour les icônes en conséquence
function updateIconsBasedOnConnection() {
  if (!navigator.onLine) {
    replaceIconsWithEmojis();
  } else {
    restoreIcons();
  }
}

// Vérifier si l'API de détection en ligne est disponible
const isOnlineDetectionSupported = 'onLine' in navigator;

// Écouter les changements d'état de la connexion
if (isOnlineDetectionSupported) {
  window.addEventListener('online', updateIconsBasedOnConnection);
  window.addEventListener('offline', updateIconsBasedOnConnection);
}

// Vérifier l'état de la connexion au chargement
document.addEventListener('DOMContentLoaded', () => {
  // Vérifier immédiatement
  updateIconsBasedOnConnection();
  
  // Vérifier à nouveau après un court délai pour s'assurer que tout est chargé
  setTimeout(updateIconsBasedOnConnection, 1000);
  
  // Vérifier périodiquement (au cas où l'événement ne se déclenche pas)
  setInterval(updateIconsBasedOnConnection, 3000);
});

// Exporter les fonctions pour un accès global (au cas où)
window.offlineIcons = {
  replace: replaceIconsWithEmojis,
  restore: restoreIcons,
  update: updateIconsBasedOnConnection
};
